#!/bin/bash

get_ordinal_suffix() {
    local day=$1
    if (( day >= 11 && day <= 13 )); then
        echo "th"
    else
        case $(( day % 10 )) in
            1) echo "st" ;;
            2) echo "nd" ;;
            3) echo "rd" ;;
            *) echo "th" ;;
        esac
    fi
}

target_time=$(date "+%Y-%m-%d %H:%M")


day=$(date -d "$target_time" "+%d" | sed 's/^0//')
week=$(date -d "$target_time" "+%a")
month=$(date -d "$target_time" "+%b")
year=$(date -d "$target_time" "+%Y")
time_hm=$(date -d "$target_time" "+%H:%M")

suffix=$(get_ordinal_suffix $day)

result="${week}.,${month}.${day}${suffix},${year},${time_hm}"

#echo "$result" |tee >(xclip -selection clipboard)
echo "$result"
#echo "git commit -m \"$result\"" | xclip -selection clipboard
